name: Build and publish phpqa images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build PHP QA Docker Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2, 8.3, 8.4, 8.5]

    steps:
      - name: Check if base image exists
        id: check
        run: |
          BASE_IMAGE="jakzal/phpqa:php${{ matrix.php-version }}"
          echo "Checking base image: $BASE_IMAGE"
          if docker manifest inspect "$BASE_IMAGE" > /dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Skipping PHP ${{ matrix.php-version }} — base image not found: $BASE_IMAGE"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit early if base image is missing
        if: steps.check.outputs.exists == 'false'
        run: exit 0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.check.outputs.exists == 'true'
        run: |
          IMAGE_NAME=ghcr.io/spomky-labs/phpqa:${{ matrix.php-version }}
          docker build --build-arg PHP_VERSION=${{ matrix.php-version }} -t $IMAGE_NAME .
          docker push $IMAGE_NAME
